# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-22 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0004_auto_20170822_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
