# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0009_auto_20170822_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Status',
            field=models.CharField(blank=True, choices=[('QUOTE', 'Quote'), ('IN PROCESS', 'In process'), ('BOOKED', 'Booked')], default='QUOTE', max_length=100, null=True),
        ),
    ]
